/* Generated By:JavaCC: Do not edit this line. REQParserTreeConstants.java Version 5.0 */
package req.transfer;

public interface REQParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTREQPARAM = 1;
  public int JJTPARAM = 2;


  public String[] jjtNodeName = {
    "parse",
    "reqParam",
    "param",
  };
}
/* JavaCC - OriginalChecksum=4f05c595c34f310949135ee25c0f836a (do not edit this line) */
